name: Update Generated MCP Tools

on:
  workflow_dispatch:
    inputs:
      api_url:
        description: "Base API URL ending with /api/v1"
        required: false
        default: ""
  schedule:
    - cron: "0 3 * * *" # daily at 03:00 UTC

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci || npm install --ignore-scripts

      - name: Determine API URL
        id: cfg
        run: |
          API_URL_INPUT="${{ github.event.inputs.api_url }}"
          if [ -n "$API_URL_INPUT" ]; then
            echo "api_url=$API_URL_INPUT" >> $GITHUB_OUTPUT
          elif [ -n "${{ secrets.N8N_API_URL }}" ]; then
            echo "api_url=${{ secrets.N8N_API_URL }}" >> $GITHUB_OUTPUT
          else
            echo "::warning::N8N_API_URL not provided; skipping generation."
            echo "api_url=" >> $GITHUB_OUTPUT
          fi

      - name: Generate tools from OpenAPI
        if: steps.cfg.outputs.api_url != ''
        env:
          N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
        run: |
          URL="${{ steps.cfg.outputs.api_url }}"
          URL_TRIMMED="${URL%/}"
          SPEC_URL="$URL_TRIMMED/docs/swagger-ui-init.js"
          echo "Fetching spec from: $SPEC_URL"
          node examples/generate-n8n-mcp-tools.js --from-url "$SPEC_URL" --out examples/generated/n8n-openapi-tools.json
          node examples/build-tools-readme.js

      - name: Validate server loads tools
        if: steps.cfg.outputs.api_url != ''
        run: node examples/mcp-n8n-server.js --once tools/list {}

      - name: Commit changes
        if: steps.cfg.outputs.api_url != ''
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(mcp): auto-generate tools from OpenAPI"
          file_pattern: |
            examples/generated/n8n-openapi-tools.json
            examples/generated/TOOLS.md

