name: Update Wiki

on:
  push:
    branches: [ main, master ]
    paths:
      - README.md
      - VIBE.md
      - CHANGELOG.md
      - SECURITY.md
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md
      - scripts/build-wiki.js
      - examples/lint-openapi.js
      - examples/scripts/lint-all-specs.js
      - examples/build-tools-readme.js
      - examples/generated/TOOLS.md
      - examples/generated/*.json
      - examples/specs/**
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: wiki-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spec-gate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [Domains, DNS, VPS]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Spec Gate (${{ matrix.tag }})
        run: node examples/scripts/spec-gate.js --file examples/specs/hostinger-api.json --runs 3 --include-tags "${{ matrix.tag }}"

  build-and-publish:
    needs: spec-gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git for wiki push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf https://github.com/

      - name: Lint OpenAPI specs (root/specs)
        run: npm run openapi:lint:all

      - name: Lint OpenAPI specs (examples/specs)
        run: |
          set -e
          shopt -s nullglob
          for f in examples/specs/*.json; do
            echo "Linting example spec $f"
            node examples/lint-openapi.js --file "$f"
          done

      - name: Spec Gate (conformance + fuzz, no network)
        run: npm run openapi:spec-gate:all

      - name: Regenerate tools from local specs
        run: |
          set -e
          shopt -s nullglob
          for f in examples/specs/*.{json,yaml,yml}; do
            echo "Generating tools from $f"
            base=$(basename "$f")
            name="${base%%.*}"
            out="examples/generated/${name}-openapi-tools.json"
            node examples/generate-openapi-mcp-tools.js --from-file "$f" --out "$out"
          done
          # Rebuild Tools README after regeneration
          npm run mcp:tools:readme

      - name: Publish Wiki
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: npm run docs:wiki
